/**
 * Syntax highlighter for markdown code blocks, emitted as JavaScript source.
 *
 * Hand-rolled, dependency-free tokenizer: per-language rule tables of sticky
 * regexes (comments, strings, numbers, keywords, types, literals, function
 * calls, operators, punctuation). The longest-match-at-position loop is
 * linear and fine for chat-sized code blocks.
 *
 * SECURITY: tokens are HTML-escaped by hlEscape() before being wrapped in
 * <span class="hl-*">, so code content can never inject markup.
 *
 * Concatenated into the single webview <script> block by html.ts BEFORE
 * markdown.ts (which calls highlightCode()). This module must not reference
 * document/vscode so it stays unit-testable via new Function().
 *
 * Pure string builder — no vscode dependency.
 * NOTE: no template literals (see Handoff-Summary.md lessons learned).
 */

export function buildHighlightScript(): string {
    return [
        // ---- Rule helpers ----
        "function hlR(re, cls) { return { re: re, cls: cls || '' }; }",
        "function hlW(words, cls) { return { re: new RegExp('(?:' + words.join('|') + ')\\\\b', 'y'), cls: cls }; }",
        "function hlCi(rules) {",
        "    return rules.map(function (r) { return { re: new RegExp(r.re.source, 'iy'), cls: r.cls }; });",
        "}",
        "function hlEscape(s) {",
        "    return String(s).replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;')",
        "        .replace(/\"/g, '&quot;').replace(/'/g, '&#39;');",
        "}",
        // ---- Shared rules (regex objects are stateless for our purposes:
        // lastIndex is always set before exec) ----
        "var HL_NUM = hlR(/\\b(?:0[xX][0-9a-fA-F_]+|\\d[\\d_]*(?:\\.\\d+)?(?:[eE][+-]?\\d+)?)(?:[uUlLfFdD]{0,3})\\b/y, 'num');",
        "var HL_NUM_PLAIN = hlR(/\\b\\d[\\d_]*(?:\\.\\d+)?(?:[eE][+-]?\\d+)?\\b/y, 'num');",
        "var HL_FN = hlR(/[A-Za-z_$][\\w$]*(?=\\s*\\()/y, 'fn');",
        "var HL_ID = hlR(/[A-Za-z_$][\\w$]*/y, '');",
        "var HL_OP = hlR(/<<=|>>=|>>>|===|!==|=>|\\*\\*|\\/\\/|->|::|\\+\\+|--|<<|>>|&&|\\|\\||[+\\-*\\/%=<>!&|^~?:]/y, 'op');",
        "var HL_PUN = hlR(/[{}\\[\\]();,.:@#]/y, 'pun');",
        "var HL_WS = hlR(/\\s+/y, '');",
        // ---- C-family builder ----
        "function hlCLike(pre, lit, kw, typ) {",
        "    var rules = (pre || []).slice();",
        "    rules.push(hlR(/\\/\\*[\\s\\S]*?(?:\\*\\/|$)/y, 'cmt'));",
        "    rules.push(hlR(/\\/\\/[^\\n]*/y, 'cmt'));",
        "    rules.push(hlR(/\"(?:[^\"\\\\\\n]|\\\\.)*\"?/y, 'str'));",
        "    rules.push(hlR(/'(?:[^'\\\\\\n]|\\\\.)*'?/y, 'str'));",
        "    rules.push(HL_NUM);",
        "    if (lit) { rules.push(hlW(lit, 'lit')); }",
        "    if (kw) { rules.push(hlW(kw, 'kw')); }",
        "    if (typ) { rules.push(hlW(typ, 'typ')); }",
        "    rules.push(HL_FN);",
        "    rules.push(HL_ID);",
        "    rules.push(HL_OP);",
        "    rules.push(HL_PUN);",
        "    rules.push(HL_WS);",
        "    return rules;",
        "}",
        // ---- Language tables ----
        "var HL_LANGS = {};",
        "var HL_ALIASES = {",
        "    js: 'javascript', jsx: 'javascript', mjs: 'javascript', cjs: 'javascript', node: 'javascript',",
        "    ts: 'typescript', tsx: 'typescript',",
        "    py: 'python', python3: 'python',",
        "    sh: 'bash', zsh: 'bash', shell: 'bash', console: 'bash', dockerfile: 'bash', makefile: 'bash',",
        "    yml: 'yaml',",
        "    htm: 'html', xhtml: 'html', vue: 'html', svelte: 'html',",
        "    svg: 'xml', xsl: 'xml', xslt: 'xml', plist: 'xml',",
        "    'c++': 'cpp', cc: 'cpp', cxx: 'cpp', hpp: 'cpp', hh: 'cpp', h: 'cpp',",
        "    cs: 'csharp', 'c#': 'csharp',",
        "    golang: 'go',",
        "    rs: 'rust',",
        "    ps1: 'powershell', pwsh: 'powershell', posh: 'powershell'",
        "};",
        "HL_LANGS.javascript = hlCLike(",
        "    [hlR(/`(?:[^`\\\\]|\\\\.)*`?/y, 'str')],",
        "    ['true', 'false', 'null', 'undefined', 'NaN', 'Infinity'],",
        "    ['break','case','catch','class','const','continue','debugger','default','delete','do','else','export','extends','finally','for','function','if','import','in','instanceof','new','return','super','switch','this','throw','try','typeof','var','void','while','with','yield','let','static','get','set','async','await','of'],",
        "    ['console','Math','JSON','Promise','Object','Array','String','Number','Boolean','Map','Set','Date','RegExp','Error','globalThis','window','document','process','require','module']",
        ");",
        "HL_LANGS.typescript = hlCLike(",
        "    [hlR(/`(?:[^`\\\\]|\\\\.)*`?/y, 'str')],",
        "    ['true', 'false', 'null', 'undefined', 'NaN', 'Infinity'],",
        "    ['break','case','catch','class','const','continue','debugger','default','delete','do','else','export','extends','finally','for','function','if','import','in','instanceof','new','return','super','switch','this','throw','try','typeof','var','void','while','with','yield','let','static','get','set','async','await','of','interface','type','enum','implements','private','public','protected','readonly','declare','abstract','namespace','as','satisfies','keyof','infer','is','override','module','asserts','unique','out'],",
        "    ['console','Math','JSON','Promise','Object','Array','String','Number','Boolean','Map','Set','Date','RegExp','Error','globalThis','window','document','process','require','module','any','unknown','never','string','number','boolean','object','symbol','bigint','Record','Partial','Readonly','Pick','Omit']",
        ");",
        "HL_LANGS.python = [",
        "    hlR(/\"\"\"[\\s\\S]*?(?:\"\"\"|$)/y, 'str'),",
        "    hlR(/'''[\\s\\S]*?(?:'''|$)/y, 'str'),",
        "    hlR(/#[^\\n]*/y, 'cmt'),",
        "    hlR(/[fFrRbBuU]{0,2}\"(?:[^\"\\\\\\n]|\\\\.)*\"?/y, 'str'),",
        "    hlR(/[fFrRbBuU]{0,2}'(?:[^'\\\\\\n]|\\\\.)*'?/y, 'str'),",
        "    HL_NUM,",
        "    hlW(['True', 'False', 'None'], 'lit'),",
        "    hlW(['and','as','assert','async','await','break','class','continue','def','del','elif','else','except','finally','for','from','global','if','import','in','is','lambda','nonlocal','not','or','pass','raise','return','try','while','with','yield','match','case'], 'kw'),",
        "    hlW(['print','len','range','str','int','float','list','dict','set','tuple','bool','type','isinstance','open','enumerate','zip','map','filter','sum','min','max','abs','super','sorted','any','all','repr','format','input','hasattr','getattr','setattr','self','cls'], 'typ'),",
        "    hlR(/@[\\w.]+/y, 'dec'),",
        "    HL_FN, HL_ID, HL_OP, HL_PUN, HL_WS",
        "];",
        "HL_LANGS.bash = [",
        "    hlR(/#[^\\n]*/y, 'cmt'),",
        "    hlR(/\"(?:[^\"\\\\\\n]|\\\\[\\s\\S])*\"?/y, 'str'),",
        "    hlR(/'[^'\\n]*'?/y, 'str'),",
        "    hlR(/\\$\\{[^}\\n]*\\}?|\\$[\\w@#?*!$-]+|`(?:[^`\\\\]|\\\\.)*`?/y, 'var'),",
        "    HL_NUM_PLAIN,",
        "    hlW(['if','then','elif','else','fi','for','while','until','do','done','case','esac','function','in','select','time','return','exit','break','continue','local','export','readonly','declare','unset','shift','trap','source','alias','eval','exec','set'], 'kw'),",
        "    hlR(/[A-Za-z_][\\w-]*/y, ''),",
        "    hlR(/&&|\\|\\||>>|<<|[|&;<>(){}\\[\\]]/y, 'pun'),",
        "    hlR(/[=+\\-*\\/%]+/y, 'op'),",
        "    HL_WS",
        "];",
        "HL_LANGS.json = [",
        "    hlR(/\"(?:[^\"\\\\\\n]|\\\\.)*\"(?=\\s*:)/y, 'atr'),",
        "    hlR(/\"(?:[^\"\\\\\\n]|\\\\.)*\"?/y, 'str'),",
        "    HL_NUM_PLAIN,",
        "    hlW(['true', 'false', 'null'], 'lit'),",
        "    hlR(/[{}\\[\\]:,]/y, 'pun'),",
        "    HL_WS",
        "];",
        "HL_LANGS.yaml = [",
        "    hlR(/#[^\\n]*/y, 'cmt'),",
        "    hlR(/\"(?:[^\"\\\\\\n]|\\\\.)*\"/y, 'str'),",
        "    hlR(/'[^'\\n]*'/y, 'str'),",
        "    HL_NUM_PLAIN,",
        "    hlW(['true', 'false', 'null', 'yes', 'no', 'on', 'off'], 'lit'),",
        "    hlR(/[\\w.\\-]+(?=\\s*:(?:\\s|$))/y, 'atr'),",
        "    hlR(/[&*][\\w\\-]+/y, 'var'),",
        "    hlR(/[A-Za-z_][\\w\\-.]*/y, ''),",
        "    hlR(/[:\\-|>]/y, 'pun'),",
        "    HL_WS",
        "];",
        "HL_LANGS.html = [",
        "    hlR(/<!--[\\s\\S]*?(?:-->|$)/y, 'cmt'),",
        "    hlR(/<\\?[\\s\\S]*?(?:\\?>|$)/y, 'dec'),",
        "    hlR(/<\\/?[A-Za-z][\\w:.-]*/y, 'tag'),",
        "    hlR(/\"(?:[^\"\\\\\\n]|\\\\.)*\"?/y, 'str'),",
        "    hlR(/'(?:[^'\\\\\\n]|\\\\.)*'?/y, 'str'),",
        "    hlR(/[\\w:.-]+(?=\\s*=)/y, 'atr'),",
        "    hlR(/&[a-zA-Z][a-zA-Z0-9]*;|&#\\d+;|&#x[0-9a-fA-F]+;/y, 'lit'),",
        "    HL_NUM_PLAIN,",
        "    hlR(/\\/?>/y, 'pun'),",
        "    hlR(/[A-Za-z][\\w:.-]*/y, ''),",
        "    hlR(/[=]/y, 'op'),",
        "    HL_WS",
        "];",
        "HL_LANGS.xml = HL_LANGS.html;",
        "HL_LANGS.css = [",
        "    hlR(/\\/\\*[\\s\\S]*?(?:\\*\\/|$)/y, 'cmt'),",
        "    hlR(/\"(?:[^\"\\\\\\n]|\\\\.)*\"?/y, 'str'),",
        "    hlR(/'(?:[^'\\\\\\n]|\\\\.)*'?/y, 'str'),",
        "    hlR(/#[0-9a-fA-F]{3,8}\\b/y, 'num'),",
        "    hlR(/@[\\w-]+/y, 'kw'),",
        "    hlR(/-?(?:\\d+\\.?\\d*|\\.\\d+)(?:px|em|rem|ex|ch|vw|vh|vmin|vmax|%|ms|s|deg|rad|grad|turn|fr|pt|pc|in|cm|mm)?\\b/y, 'num'),",
        "    hlR(/[\\w-]+(?=\\s*:)/y, 'atr'),",
        "    hlR(/\\.[\\w-]+|::?[\\w-]+|&/y, 'dec'),",
        "    hlR(/-{0,2}[A-Za-z_][\\w-]*/y, ''),",
        "    hlR(/[{}();:,]/y, 'pun'),",
        "    hlR(/[+*\\/ >~]/y, 'op'),",
        "    HL_WS",
        "];",
        "HL_LANGS.sql = hlCi([",
        "    hlR(/--[^\\n]*/y, 'cmt'),",
        "    hlR(/\\/\\*[\\s\\S]*?(?:\\*\\/|$)/y, 'cmt'),",
        "    hlR(/'(?:[^'\\n]|'')*'?/y, 'str'),",
        "    HL_NUM_PLAIN,",
        "    hlW(['SELECT','FROM','WHERE','INSERT','INTO','VALUES','UPDATE','SET','DELETE','CREATE','TABLE','DROP','ALTER','ADD','COLUMN','JOIN','INNER','LEFT','RIGHT','FULL','OUTER','CROSS','ON','AS','AND','OR','NOT','NULL','IS','IN','LIKE','ILIKE','BETWEEN','EXISTS','GROUP','BY','ORDER','HAVING','LIMIT','OFFSET','DISTINCT','UNION','ALL','CASE','WHEN','THEN','ELSE','END','PRIMARY','KEY','FOREIGN','REFERENCES','DEFAULT','CHECK','UNIQUE','CONSTRAINT','INDEX','VIEW','TRIGGER','PROCEDURE','FUNCTION','RETURNS','BEGIN','COMMIT','ROLLBACK','TRANSACTION','WITH','RECURSIVE','ASC','DESC','IF','PARTITION','OVER','WINDOW','GRANT','REVOKE','USE','DATABASE','SHOW','DESCRIBE','EXPLAIN'], 'kw'),",
        "    hlW(['COUNT','SUM','AVG','MIN','MAX','COALESCE','CAST','NOW','CURRENT_DATE','CURRENT_TIMESTAMP','ROW_NUMBER','RANK','DENSE_RANK'], 'fn'),",
        "    hlR(/[A-Za-z_][\\w$]*(?=\\s*\\()/y, 'fn'),",
        "    hlR(/[A-Za-z_][\\w$]*/y, ''),",
        "    hlR(/[(),;]/y, 'pun'),",
        "    hlR(/[=<>!+\\-*\\/|]/y, 'op'),",
        "    HL_WS",
        "]);",
        "HL_LANGS.powershell = [",
        "    hlR(/<#[\\s\\S]*?(?:#>|$)/y, 'cmt'),",
        "    hlR(/#[^\\n]*/y, 'cmt'),",
        "    hlR(/\"(?:[^\"`\\n]|`.)*\"?/y, 'str'),",
        "    hlR(/'(?:[^'\\n]|'')*'?/y, 'str'),",
        "    hlR(/\\$\\{[^}\\n]*\\}?|\\$[\\w:]+/y, 'var'),",
        "    HL_NUM_PLAIN,",
        "    hlW(['begin','break','catch','class','continue','data','define','do','dynamicparam','else','elseif','end','enum','exit','filter','finally','for','foreach','from','function','hidden','if','in','param','process','return','static','switch','throw','trap','try','until','using','var','while','workflow'], 'kw'),",
        "    hlR(/-[A-Za-z][\\w-]*/y, 'atr'),",
        "    hlR(/[A-Za-z_][\\w-]*(?=\\s*\\()/y, 'fn'),",
        "    hlR(/[A-Za-z_][\\w.\\-]*/y, ''),",
        "    hlR(/[{}\\[\\]();,]/y, 'pun'),",
        "    hlR(/[=<>!+\\-*\\/%&|]/y, 'op'),",
        "    HL_WS",
        "];",
        "HL_LANGS.c = hlCLike(null,",
        "    ['true', 'false', 'NULL'],",
        "    ['auto','break','case','char','const','continue','default','do','double','else','enum','extern','float','for','goto','if','inline','int','long','register','restrict','return','short','signed','sizeof','static','struct','switch','typedef','union','unsigned','void','volatile','while'],",
        "    ['char','double','float','int','long','short','signed','unsigned','void','size_t','ssize_t','int8_t','int16_t','int32_t','int64_t','uint8_t','uint16_t','uint32_t','uint64_t','bool','FILE','DIR']",
        ");",
        "HL_LANGS.cpp = hlCLike(null,",
        "    ['true', 'false', 'nullptr', 'NULL'],",
        "    ['auto','break','case','char','const','continue','default','do','double','else','enum','extern','float','for','goto','if','inline','int','long','register','restrict','return','short','signed','sizeof','static','struct','switch','typedef','union','unsigned','void','volatile','while','class','namespace','template','typename','using','public','private','protected','virtual','override','final','friend','new','delete','this','try','catch','throw','operator','constexpr','consteval','noexcept','explicit','mutable','concept','requires','co_await','co_yield','co_return'],",
        "    ['char','double','float','int','long','short','signed','unsigned','void','size_t','ssize_t','int8_t','int16_t','int32_t','int64_t','uint8_t','uint16_t','uint32_t','uint64_t','bool','FILE','std','string','vector','map','set','unordered_map','unordered_set','array','unique_ptr','shared_ptr','make_unique','make_shared','string_view','optional','variant','function']",
        ");",
        "HL_LANGS.java = hlCLike(null,",
        "    ['true', 'false', 'null'],",
        "    ['abstract','assert','boolean','break','byte','case','catch','char','class','const','continue','default','do','double','else','enum','extends','final','finally','float','for','goto','if','implements','import','instanceof','int','interface','long','native','new','package','private','protected','public','return','short','static','strictfp','super','switch','synchronized','this','throw','throws','transient','try','void','volatile','while','var','record','sealed','permits','yield'],",
        "    ['String','Object','Integer','Long','Double','Float','Boolean','Character','Byte','Short','Number','List','Map','Set','ArrayList','LinkedList','HashMap','HashSet','TreeMap','TreeSet','Optional','Stream','Exception','RuntimeException','Throwable','Runnable','Thread','System','Math','StringBuilder']",
        ");",
        "HL_LANGS.csharp = hlCLike(null,",
        "    ['true', 'false', 'null'],",
        "    ['abstract','as','base','bool','break','byte','case','catch','char','checked','class','const','continue','decimal','default','delegate','do','double','else','enum','event','explicit','extern','finally','fixed','float','for','foreach','goto','if','implicit','in','int','interface','internal','is','lock','long','namespace','new','object','operator','out','override','params','private','protected','public','readonly','ref','return','sbyte','sealed','short','sizeof','stackalloc','static','string','struct','switch','this','throw','try','typeof','uint','ulong','unchecked','unsafe','ushort','using','var','virtual','void','volatile','while','async','await','get','set','value','when','where','select','from','let','record','init','required'],",
        "    ['String','Object','Int32','Int64','Double','Boolean','Char','Byte','List','Dictionary','HashSet','IEnumerable','ICollection','IList','Task','Action','Func','Console','Math','DateTime','TimeSpan','StringBuilder','Uri','Guid','Exception','ArgumentException','InvalidOperationException']",
        ");",
        "HL_LANGS.go = hlCLike(",
        "    [hlR(/`[^`]*`?/y, 'str')],",
        "    ['true', 'false', 'nil', 'iota'],",
        "    ['break','case','chan','const','continue','default','defer','else','fallthrough','for','func','go','goto','if','import','interface','map','package','range','return','select','struct','switch','type','var'],",
        "    ['bool','byte','complex64','complex128','error','float32','float64','int','int8','int16','int32','int64','rune','string','uint','uint8','uint16','uint32','uint64','uintptr','any','comparable','append','cap','close','copy','delete','imag','len','make','new','panic','print','println','real','recover']",
        ");",
        "HL_LANGS.rust = [",
        "    hlR(/#!?\\[[^\\]\\n]*\\]?/y, 'dec'),",
        "    hlR(/\\/\\*[\\s\\S]*?(?:\\*\\/|$)/y, 'cmt'),",
        "    hlR(/\\/\\/[^\\n]*/y, 'cmt'),",
        "    hlR(/b?\"(?:[^\"\\\\]|\\\\.)*\"?/y, 'str'),",
        "    hlR(/b?'(?:[^'\\\\]|\\\\.)*'/y, 'str'),",
        "    hlR(/r#*\"[\\s\\S]*?\"#*/y, 'str'),",
        "    hlR(/'[a-zA-Z_]\\w*\\b/y, 'typ'),",
        "    HL_NUM,",
        "    hlW(['true', 'false'], 'lit'),",
        "    hlW(['as','async','await','break','const','continue','crate','dyn','else','enum','extern','fn','for','if','impl','in','let','loop','match','mod','move','mut','pub','ref','return','self','static','struct','super','trait','type','unsafe','use','where','while'], 'kw'),",
        "    hlW(['bool','char','str','u8','u16','u32','u64','u128','usize','i8','i16','i32','i64','i128','isize','f32','f64','String','Vec','Option','Result','Box','Rc','Arc','Cow','HashMap','HashSet','BTreeMap','Path','PathBuf','None','Some','Ok','Err'], 'typ'),",
        "    hlR(/[A-Za-z_]\\w*(?=\\s*!)/y, 'dec'),",
        "    hlR(/[A-Za-z_]\\w*(?=\\s*\\()/y, 'fn'),",
        "    hlR(/[A-Za-z_]\\w*/y, ''),",
        "    hlR(/::|->|=>|\\.\\.=|\\.\\.|<<=|>>=|&&|\\|\\||[+\\-*\\/%=<>!&|^?]/y, 'op'),",
        "    hlR(/[{}\\[\\]();,.@#]/y, 'pun'),",
        "    HL_WS",
        "];",
        // ---- Language guessing for untagged fences ----
        "function hlGuess(code) {",
        "    var s = String(code == null ? '' : code).replace(/^\\s+/, '');",
        "    if (!s) { return ''; }",
        "    if (/^<\\?xml/i.test(s)) { return 'xml'; }",
        "    if (/^<!doctype html/i.test(s) || /^<html[\\s>]/i.test(s)) { return 'html'; }",
        "    if (/^#!/.test(s)) {",
        "        if (/python/.test(s)) { return 'python'; }",
        "        return 'bash';",
        "    }",
        "    if (/^[{\\[]/.test(s)) { return 'json'; }",
        "    return '';",
        "}",
        "function normalizeLang(lang) {",
        "    if (!lang) { return ''; }",
        "    var l = String(lang).toLowerCase().trim();",
        "    if (HL_LANGS[l]) { return l; }",
        "    if (HL_ALIASES[l]) { return HL_ALIASES[l]; }",
        "    return l;",
        "}",
        // ---- The tokenizer ----
        "function highlightCode(code, lang) {",
        "    code = String(code == null ? '' : code);",
        "    var l = normalizeLang(lang);",
        "    if (!l) { l = hlGuess(code); }",
        "    var rules = HL_LANGS[l];",
        "    if (!rules) { return hlEscape(code); }",
        "    var out = [];",
        "    var i = 0;",
        "    while (i < code.length) {",
        "        var matched = null;",
        "        var cls = '';",
        "        for (var r = 0; r < rules.length; r++) {",
        "            var rule = rules[r];",
        "            rule.re.lastIndex = i;",
        "            var m = rule.re.exec(code);",
        "            if (m && m[0].length > 0) { matched = m[0]; cls = rule.cls; break; }",
        "        }",
        "        if (matched === null) {",
        "            out.push(hlEscape(code.charAt(i)));",
        "            i += 1;",
        "            continue;",
        "        }",
        "        if (cls) { out.push('<span class=\"hl-' + cls + '\">' + hlEscape(matched) + '</span>'); }",
        "        else { out.push(hlEscape(matched)); }",
        "        i += matched.length;",
        "    }",
        "    return out.join('');",
        "}",
    ].join("\n");
}