/**
 * Markdown renderer for the chat webview, emitted as JavaScript source.
 *
 * Hand-rolled, dependency-free Markdown-to-HTML renderer: headings,
 * bold/italic/strike, inline code, fenced code blocks with language header
 * (syntax-highlighted by highlightCode() from highlight.ts), blockquotes,
 * nested ordered/unordered lists, GFM tables with alignment, http(s) links,
 * horizontal rules.
 *
 * SECURITY: text is HTML-escaped FIRST, so model output can never inject
 * markup; the transforms below re-introduce only a safe, known subset of
 * tags. Link hrefs are restricted to http/https. Fenced code is extracted
 * from the RAW text before escaping and highlighted by highlightCode(),
 * which escapes token content itself.
 *
 * Pure string builder — no vscode dependency, unit-testable.
 * NOTE: no template literals (see Handoff-Summary.md lessons learned).
 */

export function buildMarkdownScript(): string {
    return [
        "var mdCodeBlocks = [];",
        "function escapeHtml(s) {",
        "    return String(s)",
        "        .replace(/&/g, '&amp;')",
        "        .replace(/</g, '&lt;')",
        "        .replace(/>/g, '&gt;')",
        "        .replace(/\"/g, '&quot;')",
        "        .replace(/'/g, '&#39;');",
        "}",
        "function mdInline(s) {",
        "    var codes = [];",
        "    s = s.replace(/`([^`\\n]+)`/g, function (m, c) {",
        "        codes.push('<code class=\"md-code\">' + c + '</code>');",
        "        return '\\x00C' + (codes.length - 1) + '\\x00';",
        "    });",
        "    s = s.replace(/\\[([^\\]]+)\\]\\((https?:\\/\\/[^\\s)]+)\\)/g, function (m, t, u) {",
        "        return '<a href=\"' + u + '\" target=\"_blank\" rel=\"noopener noreferrer\">' + t + '</a>';",
        "    });",
        "    s = s.replace(/(^|[\\s(])(https?:\\/\\/[^\\s<)]+)/g, function (m, p, u) {",
        "        return p + '<a href=\"' + u + '\" target=\"_blank\" rel=\"noopener noreferrer\">' + u + '</a>';",
        "    });",
        "    s = s.replace(/\\*\\*([^*]+)\\*\\*/g, '<strong>$1</strong>');",
        "    s = s.replace(/(^|[^A-Za-z0-9])\\*([^*\\n]+)\\*(?![A-Za-z0-9])/g, '$1<em>$2</em>');",
        "    s = s.replace(/(^|\\s)_([^_\\n]+)_(?=\\s|$|[.,;:!?])/g, '$1<em>$2</em>');",
        "    s = s.replace(/~~([^~\\n]+)~~/g, '<del>$1</del>');",
        "    s = s.replace(/\\x00C(\\d+)\\x00/g, function (m, n) { return codes[Number(n)]; });",
        "    return s;",
        "}",
        "function mdRenderCode(idx) {",
        "    var b = mdCodeBlocks[idx];",
        "    if (!b) { return ''; }",
        "    var bodyHtml = (typeof highlightCode === 'function') ? highlightCode(b.code, b.lang) : escapeHtml(b.code);",
        "    return '<div class=\"md-codeblock\"><div class=\"md-codehead\">' + escapeHtml(b.lang || 'code') + '</div><pre>' + bodyHtml + '</pre></div>';",
        "}",
        "function mdExtractFences(src) {",
        "    src = src.replace(/```([\\w+#-]*)[ \\t]*\\n([\\s\\S]*?)```/g, function (m, lang, code) {",
        "        mdCodeBlocks.push({ lang: lang, code: code.replace(/\\n$/, '') });",
        "        return '\\n\\x00B' + (mdCodeBlocks.length - 1) + '\\x00\\n';",
        "    });",
        "    src = src.replace(/```([\\w+#-]*)[ \\t]*\\n([\\s\\S]*)$/g, function (m, lang, code) {",
        "        mdCodeBlocks.push({ lang: lang, code: code.replace(/\\n$/, '') });",
        "        return '\\n\\x00B' + (mdCodeBlocks.length - 1) + '\\x00\\n';",
        "    });",
        "    return src;",
        "}",
        "function splitTableRow(row) {",
        "    var s = row.trim();",
        "    if (s.charAt(0) === '|') { s = s.substring(1); }",
        "    if (s.length > 0 && s.charAt(s.length - 1) === '|') { s = s.substring(0, s.length - 1); }",
        "    return s.split('|');",
        "}",
        "function renderTable(lines, start) {",
        "    var header = splitTableRow(lines[start].trim());",
        "    var aligns = splitTableRow(lines[start + 1].trim()).map(function (c) {",
        "        var cc = c.trim();",
        "        var left = cc.charAt(0) === ':';",
        "        var right = cc.charAt(cc.length - 1) === ':';",
        "        return (left && right) ? 'center' : (right ? 'right' : 'left');",
        "    });",
        "    var i = start + 2;",
        "    var rows = [];",
        "    while (i < lines.length) {",
        "        var tt = lines[i].trim();",
        "        if (tt === '' || tt.indexOf('|') === -1) { break; }",
        "        if (/^\\x00B\\d+\\x00$/.test(tt)) { break; }",
        "        rows.push(splitTableRow(tt));",
        "        i++;",
        "    }",
        "    var h = '<div class=\"md-tablewrap\"><table class=\"md-table\"><thead><tr>';",
        "    header.forEach(function (c, ci) {",
        "        h += '<th style=\"text-align:' + (aligns[ci] || 'left') + '\">' + mdInline(c.trim()) + '</th>';",
        "    });",
        "    h += '</tr></thead><tbody>';",
        "    rows.forEach(function (r) {",
        "        h += '<tr>';",
        "        for (var ci = 0; ci < header.length; ci++) {",
        "            h += '<td style=\"text-align:' + (aligns[ci] || 'left') + '\">' + mdInline((r[ci] || '').trim()) + '</td>';",
        "        }",
        "        h += '</tr>';",
        "    });",
        "    h += '</tbody></table></div>';",
        "    return { html: h, next: i };",
        "}",
        "function matchList(t, rawLine) {",
        "    var m = t.match(/^([-*+]|\\d+[.)])\\s+(.*)$/);",
        "    if (!m) { return null; }",
        "    var indent = rawLine.match(/^ */)[0].length;",
        "    return { indent: indent, ordered: /^\\d/.test(t), content: m[2] };",
        "}",
        "function renderList(lines, start) {",
        "    var html = '';",
        "    var stack = [];",
        "    var openLi = false;",
        "    var i = start;",
        "    function closeLi() {",
        "        if (openLi) { html += '</li>'; openLi = false; }",
        "    }",
        "    while (i < lines.length) {",
        "        var raw = lines[i];",
        "        var t = raw.trim();",
        "        if (t === '') {",
        "            var j = i + 1;",
        "            while (j < lines.length && lines[j].trim() === '') { j++; }",
        "            if (j < lines.length && matchList(lines[j].trim(), lines[j])) { i = j; continue; }",
        "            break;",
        "        }",
        "        var lm = matchList(t, raw);",
        "        if (lm) {",
        "            if (stack.length === 0) {",
        "                stack.push({ indent: lm.indent, ordered: lm.ordered });",
        "                html += lm.ordered ? '<ol>' : '<ul>';",
        "            } else {",
        "                while (stack.length > 0 && lm.indent < stack[stack.length - 1].indent - 1) {",
        "                    closeLi();",
        "                    html += stack[stack.length - 1].ordered ? '</ol>' : '</ul>';",
        "                    stack.pop();",
        "                    openLi = stack.length > 0;",
        "                }",
        "                if (stack.length === 0) {",
        "                    stack.push({ indent: lm.indent, ordered: lm.ordered });",
        "                    html += lm.ordered ? '<ol>' : '<ul>';",
        "                } else if (lm.indent > stack[stack.length - 1].indent + 1) {",
        "                    stack.push({ indent: lm.indent, ordered: lm.ordered });",
        "                    html += lm.ordered ? '<ol>' : '<ul>';",
        "                } else {",
        "                    closeLi();",
        "                }",
        "            }",
        "            html += '<li>' + mdInline(lm.content);",
        "            openLi = true;",
        "            i++;",
        "            continue;",
        "        }",
        "        var isCont = false;",
        "        if (stack.length > 0 && openLi) {",
        "            if (/^( {2,}|\\t)/.test(raw)) { isCont = true; }",
        "            else if (/^\\x00B\\d+\\x00$/.test(t)) { isCont = true; }",
        "        }",
        "        if (isCont) {",
        "            html += '<br>' + (/^\\x00B\\d+\\x00$/.test(t) ? t : mdInline(t));",
        "            i++;",
        "            continue;",
        "        }",
        "        break;",
        "    }",
        "    while (stack.length > 0) {",
        "        closeLi();",
        "        html += stack[stack.length - 1].ordered ? '</ol>' : '</ul>';",
        "        stack.pop();",
        "        openLi = stack.length > 0;",
        "    }",
        "    return { html: html, next: i };",
        "}",
        "function mdRenderEscaped(src) {",
        "    var lines = src.split('\\n');",
        "    var out = [];",
        "    var para = [];",
        "    function flushPara() {",
        "        if (para.length > 0) {",
        "            out.push('<p>' + mdInline(para.join('\\n')).replace(/\\n/g, '<br>') + '</p>');",
        "            para = [];",
        "        }",
        "    }",
        "    var i = 0;",
        "    while (i < lines.length) {",
        "        var line = lines[i];",
        "        var t = line.trim();",
        "        var cbm = t.match(/^\\x00B(\\d+)\\x00$/);",
        "        if (cbm) {",
        "            flushPara();",
        "            out.push(mdRenderCode(Number(cbm[1])));",
        "            i++;",
        "            continue;",
        "        }",
        "        if (t === '') {",
        "            flushPara();",
        "            i++;",
        "            continue;",
        "        }",
        "        var hm = t.match(/^(#{1,6})\\s+(.*)$/);",
        "        if (hm) {",
        "            flushPara();",
        "            out.push('<h' + hm[1].length + '>' + mdInline(hm[2]) + '</h' + hm[1].length + '>');",
        "            i++;",
        "            continue;",
        "        }",
        "        if (/^(-{3,}|\\*{3,}|_{3,})$/.test(t)) {",
        "            flushPara();",
        "            out.push('<hr>');",
        "            i++;",
        "            continue;",
        "        }",
        "        if (/^&gt;/.test(t)) {",
        "            flushPara();",
        "            var q = [];",
        "            while (i < lines.length && /^&gt;/.test(lines[i].trim())) {",
        "                q.push(lines[i].trim().replace(/^&gt;\\s?/, ''));",
        "                i++;",
        "            }",
        "            out.push('<blockquote>' + mdRenderEscaped(q.join('\\n')) + '</blockquote>');",
        "            continue;",
        "        }",
        "        if (t.indexOf('|') !== -1 && i + 1 < lines.length &&",
        "            /^\\s*\\|?\\s*:?-{2,}:?\\s*(\\|\\s*:?-{2,}:?\\s*)+\\|?\\s*$/.test(lines[i + 1])) {",
        "            flushPara();",
        "            var tr = renderTable(lines, i);",
        "            out.push(tr.html);",
        "            i = tr.next;",
        "            continue;",
        "        }",
        "        var lm = matchList(t, line);",
        "        if (lm) {",
        "            flushPara();",
        "            var lr = renderList(lines, i);",
        "            out.push(lr.html);",
        "            i = lr.next;",
        "            continue;",
        "        }",
        "        para.push(t);",
        "        i++;",
        "    }",
        "    flushPara();",
        "    return out.join('\\n');",
        "}",
        "function mdRender(text) {",
        "    if (text === undefined || text === null) { text = ''; }",
        "    mdCodeBlocks = [];",
        "    var src = String(text).replace(/\\r\\n?/g, '\\n');",
        "    src = mdExtractFences(src);",
        "    src = escapeHtml(src);",
        "    var html = mdRenderEscaped(src);",
        "    html = html.replace(/\\x00B(\\d+)\\x00/g, function (m, n) { return mdRenderCode(Number(n)); });",
        "    return html;",
        "}",
    ].join("\n");
}