/**
 * Webview "shell" script: element refs, persisted state (draft/height/scroll),
 * Up/Down prompt history, setup-overlay wiring, status/debug helpers, model
 * dropdown, boot handshake, and input controls (Send/Stop/keyboard).
 *
 * Concatenated with markdown.ts and messages.ts into one <script> block by
 * html.ts. This part must come FIRST (it opens with "use strict" and declares
 * the shared variables used by the other parts).
 *
 * Pure string builder — no vscode dependency, unit-testable.
 * NOTE: no template literals (see Handoff-Summary.md lessons learned).
 */

export function buildWebviewScript(): string {
    return [
        '"use strict";',
        "var vscode = acquireVsCodeApi();",
        "var statusEl = document.getElementById('status');",
        "var messages = document.getElementById('messages');",
        "var input = document.getElementById('input');",
        "var inputGrip = document.getElementById('inputGrip');",
        "var send = document.getElementById('send');",
        "var stop = document.getElementById('stop');",
        "var modelSelect = document.getElementById('modelSelect');",
        "var actionMenu = document.getElementById('actionMenu');",
        "var setupOverlay = document.getElementById('setupOverlay');",
        "var setupBaseUrl = document.getElementById('setupBaseUrl');",
        "var setupAuthType = document.getElementById('setupAuthType');",
        "var setupAuthLabel = document.getElementById('setupAuthLabel');",
        "var setupAuthValue = document.getElementById('setupAuthValue');",
        "var setupTestBtn = document.getElementById('setupTestBtn');",
        "var setupStatus = document.getElementById('setupStatus');",
        "var setupModelSelect = document.getElementById('setupModelSelect');",
        "var setupMaxSteps = document.getElementById('setupMaxSteps');",
        "var setupSaveBtn = document.getElementById('setupSaveBtn');",
        "var debugToggle = document.getElementById('debugToggle');",
        "var debugWrap = document.getElementById('debugWrap');",
        "var addFileBtn = document.getElementById('addFileBtn');",
        "var fileAttachMenu = document.getElementById('fileAttachMenu');",
        "var attachAtPos = -1;",

        // Retained as null to prevent ReferenceErrors in messages.ts
        "var refreshModels = null;",
        "var timeModels = null;",
        "var compactBtn = null;",
        "var clearChatBtn = null;",
        "var settingsBtn = null;",

        "var line = 0;",
        "var knownModels = [];",
        "var timings = {};",

        // ---- Webview state persistence (survives view hide/show cycles) ----
        "var agentRunning = false;",
        "var savedState = null;",
        "try { savedState = vscode.getState(); } catch (e) { savedState = null; }",
        "var heightApplied = false;",
        "if (savedState && typeof savedState.draft === 'string' && input) { input.value = savedState.draft; }",
        "if (savedState && typeof savedState.inputHeight === 'number' && savedState.inputHeight >= 48 && input) {",
        "    input.style.height = savedState.inputHeight + 'px';",
        "    heightApplied = true;",
        "}",

        // ---- Prompt history (Up/Down navigation) ----
        "var promptHistory = [];",
        "var historyIndex = 0;",
        "var pendingDraft = '';",
        "var draftTimer = null;",
        "var heightTimer = null;",
        "function sendDraftNow() {",
        "    try { vscode.postMessage({ type: 'draftChange', text: input ? input.value : '' }); } catch (e) {}",
        "}",
        "function sendDraftDebounced() {",
        "    if (draftTimer) { clearTimeout(draftTimer); }",
        "    draftTimer = setTimeout(sendDraftNow, 300);",
        "}",
        "function sendHeightNow() {",
        "    if (!input) { return; }",
        "    var h = input.offsetHeight || input.getBoundingClientRect().height;",
        "    if (h > 0) { try { vscode.postMessage({ type: 'inputHeightChange', height: Math.round(h) }); } catch (e) {} }",
        "}",
        "function saveViewState() {",
        "    try {",
        "        var atBottom = messages ? (messages.scrollHeight - messages.scrollTop - messages.clientHeight < 40) : true;",
        "        vscode.setState({",
        "            draft: input ? input.value : '',",
        "            scrollTop: messages ? messages.scrollTop : 0,",
        "            atBottom: atBottom,",
        "            inputHeight: input ? Math.round(input.offsetHeight || input.getBoundingClientRect().height) : 0",
        "        });",
        "    } catch (e) {}",
        "}",
        "if (window.ResizeObserver && input) {",
        "    new ResizeObserver(function () {",
        "        if (heightTimer) { clearTimeout(heightTimer); }",
        "        heightTimer = setTimeout(sendHeightNow, 400);",
        "    }).observe(input);",
        "}",
        "if (input) {",
        "    input.addEventListener('input', function () { sendDraftDebounced(); saveViewState(); });",
        "}",
        "if (messages) { messages.addEventListener('scroll', saveViewState); }",

        // ---- Input box resize grip (full horizontal line) ----
        "var gripDragging = false;",
        "var gripStartY = 0;",
        "var gripStartHeight = 0;",
        "function gripClampHeight(h) {",
        "    var maxH = Math.round((window.innerHeight || 0) * 0.7);",
        "    if (h < 48) { return 48; }",
        "    if (maxH > 48 && h > maxH) { return maxH; }",
        "    return h;",
        "}",
        "if (inputGrip) {",
        "    inputGrip.addEventListener('pointerdown', function (e) {",
        "        if (!input) { return; }",
        "        e.preventDefault();",
        "        e.stopPropagation();",
        "        gripDragging = true;",
        "        gripStartY = e.clientY;",
        "        gripStartHeight = input.offsetHeight || Math.round(input.getBoundingClientRect().height);",
        "        inputGrip.classList.add('grip-active');",
        "        document.body.style.cursor = 'ns-resize';",
        "        document.body.style.userSelect = 'none';",
        "    });",
        "}",
        "window.addEventListener('pointermove', function (e) {",
        "    if (!gripDragging || !input) { return; }",
        "    e.preventDefault();",
        "    var delta = gripStartY - e.clientY;",
        "    var newH = gripClampHeight(gripStartHeight + delta);",
        "    input.style.height = newH + 'px';",
        "});",
        "function stopGripDrag(e) {",
        "    if (!gripDragging) { return; }",
        "    gripDragging = false;",
        "    if (inputGrip) { inputGrip.classList.remove('grip-active'); }",
        "    document.body.style.cursor = '';",
        "    document.body.style.userSelect = '';",
        "    sendHeightNow();",
        "    saveViewState();",
        "}",
        "window.addEventListener('pointerup', stopGripDrag);",
        "window.addEventListener('pointercancel', stopGripDrag);",

        "function caretToEnd() {",
        "    try { input.selectionStart = input.selectionEnd = input.value.length; } catch (e) {}",
        "}",
"function canNavigateHistoryUp() {",
        "    if (!input) { return false; }",
        "    var start = input.selectionStart || 0;",
        "    var end = input.selectionEnd || 0;",
        "    if (start !== end) { return false; }",
        "    return start === 0;",
        "}",
        "function canNavigateHistoryDown() {",
        "    if (!input) { return false; }",
        "    var start = input.selectionStart || 0;",
        "    var end = input.selectionEnd || 0;",
        "    if (start !== end) { return false; }",
        "    return start === input.value.length;",
        "}",
        "function caretToStart() {",
        "    try { input.selectionStart = input.selectionEnd = 0; } catch (e) {}",
        "}",
        "function caretToEnd() {",
        "    try { input.selectionStart = input.selectionEnd = input.value.length; } catch (e) {}",
        "}",
        "function historyOlder() {",
        "    if (!input || promptHistory.length === 0 || historyIndex === 0) { return false; }",
        "    if (historyIndex === promptHistory.length) { pendingDraft = input.value; }",
        "    historyIndex--;",
        "    input.value = promptHistory[historyIndex];",
        "    caretToStart();",
        "    sendDraftDebounced();",
        "    saveViewState();",
        "    return true;",
        "}",
        "function historyNewer() {",
        "    if (!input || historyIndex >= promptHistory.length) { return false; }",
        "    historyIndex++;",
        "    if (historyIndex === promptHistory.length) {",
        "        input.value = pendingDraft;",
        "    } else {",
        "        input.value = promptHistory[historyIndex];",
        "    }",
        "    caretToEnd();",
        "    sendDraftDebounced();",
        "    saveViewState();",
        "    return true;",
        "}",
        // ---- Setup overlay wiring ----
        "function updateSetupAuthInput(authType, authValue, apiKeyStored) {",
        "  if (!setupAuthLabel || !setupAuthValue) { return; }",
        "  if (authType === 'env') {",
        "    setupAuthLabel.textContent = 'Env Var Name'; setupAuthValue.placeholder = 'e.g. OPENAI_API_KEY'; setupAuthValue.type = 'text';",
        "    if (authValue !== undefined) { setupAuthValue.value = authValue; }",
        "  } else {",
        "    setupAuthLabel.textContent = 'API Key'; setupAuthValue.type = 'password';",
        "    setupAuthValue.placeholder = apiKeyStored ? 'Stored securely; enter only to replace' : 'sk-...';",
        "    if (authValue !== undefined) { setupAuthValue.value = ''; }",
        "  }",
        "}",
        "if(setupAuthType) {",
        "  setupAuthType.addEventListener('change', function() {",
        "    updateSetupAuthInput(this.value, '', false);",
        "  });",
        "}",
        "if(setupTestBtn) {",
        "  setupTestBtn.addEventListener('click', function() {",
        "    setupStatus.textContent = 'Testing...'; setupStatus.style.color = 'var(--vscode-descriptionForeground)';",
        "    vscode.postMessage({ type: 'testConnection', baseUrl: setupBaseUrl.value, authType: setupAuthType.value, authValue: setupAuthValue.value });",
        "  });",
        "}",
        "if(setupSaveBtn) {",
        "  setupSaveBtn.addEventListener('click', function() {",
        "    vscode.postMessage({ type: 'saveSetup', baseUrl: setupBaseUrl.value, authType: setupAuthType.value, authValue: setupAuthValue.value, model: setupModelSelect.value, maxSteps: setupMaxSteps ? setupMaxSteps.value : '25' });",
        "  });",
        "}",

        // ---- Status banner / debug log ----
        "function setStatus(t, cls) {",
        "    if (statusEl) { statusEl.textContent = t;",
        "        statusEl.className = cls || 'st';",
        "        statusEl.style.display = 'block'; }",
        "}",
        "function logLine(t) {",
        "    line++;",
        "    var d = document.createElement('div');",
        "    d.textContent = line + ': ' + t;",
        "    d.className = 'dbg';",
        "    var dbg = document.getElementById('debug');",
        "    if (dbg) { dbg.appendChild(d); dbg.scrollTop = dbg.scrollHeight; }",
        "}",
        "if (debugToggle && debugWrap) {",
        "    debugToggle.addEventListener('click', function () {",
        "        var collapsed = debugWrap.classList.toggle('collapsed');",
        "        debugToggle.textContent = collapsed ? '▸ debug log' : '▾ debug log';",
        "    });",
        "}",

        // ---- Model dropdown helpers ----
        "function labelFor(m) {",
        "    var t = timings[m];",
        "    if (t === undefined) { return m; }",
        "    if (t === null) { return m + '  (timing...)'; }",
        "    if (t < 0) { return m + '  (failed)'; }",
        "    return m + '  (' + t + ' ms)';",
        "}",
        "function renderModelOptions() {",
        "    if (!modelSelect) { return; }",
        "    var keep = modelSelect.value;",
        "    modelSelect.innerHTML = '';",
        "    knownModels.forEach(function (m) {",
        "        var opt = document.createElement('option');",
        "        opt.value = m;",
        "        opt.textContent = labelFor(m);",
        "        if (m === keep) { opt.selected = true; }",
        "        modelSelect.appendChild(opt);",
        "    });",
        "}",
        "function updateModelOptions(models, selected) {",
        "    if (!modelSelect) { return; }",
        "    var list = Array.isArray(models) ? models.slice() : [];",
        "    if (selected && list.indexOf(selected) === -1) {",
        "        list.unshift(selected);",
        "    }",
        "    if (list.length === 0 && selected) {",
        "        list.push(selected);",
        "    }",
        "    knownModels = list;",
        "    modelSelect.innerHTML = '';",
        "    list.forEach(function (m) {",
        "        var opt = document.createElement('option');",
        "        opt.value = m;",
        "        opt.textContent = labelFor(m);",
        "        if (m === selected) { opt.selected = true; }",
        "        modelSelect.appendChild(opt);",
        "    });",
        "}",

        // ---- Boot handshake ----
        "window.onerror = function (msg, src, l, c) {",
        "    var t = 'SCRIPT ERROR: ' + msg + ' @' + l + ':' + c;",
        "    setStatus('SCRIPT ERROR (see debug)', 'st-err');",
        "    logLine(t);",
        "    try { vscode.postMessage({ type: 'webviewError', text: t }); } catch (e) {}",
        "    return false;",
        "};",
        "logLine('script started');",
        "setStatus('WEBVIEW ALIVE - script running', 'st-ok');",
        "try {",
        "    vscode.postMessage({",
        "        type: 'webviewReady',",
        "        draft: input ? input.value : '',",
        "        height: input ? Math.round(input.offsetHeight || input.getBoundingClientRect().height) : 0",
        "    });",
        "    logLine('webviewReady sent');",
        "}",
        "catch (e) { logLine('postMessage failed: ' + e); }",

        // ---- Menu Action Dispatch ----
        "if (actionMenu) {",
        "    actionMenu.addEventListener('change', function () {",
        "        var val = actionMenu.value;",
        "        actionMenu.value = '';",
        "        if (val === 'refresh') {",
        "            vscode.postMessage({ type: 'fetchModels' });",
        "            setStatus('fetching models...', 'st-wait');",
        "        } else if (val === 'time') {",
        "            knownModels.forEach(function (m) { timings[m] = null; });",
        "            renderModelOptions();",
        "            vscode.postMessage({ type: 'benchmarkModels' });",
        "            setStatus('measuring model response times...', 'st-wait');",
        "        } else if (val === 'compact') {",
        "            vscode.postMessage({ type: 'compact' });",
        "            setStatus('compacting context...', 'st-wait');",
        "        } else if (val === 'clear') {",
        "            // window.confirm() is blocked by the webview sandbox, so we",
        "            // delegate confirmation to the host (native VS Code modal).",
        "            // The host posts 'clearChat' back only after the user confirms,",
        "            // at which point the message handler clears the rendered bubbles.",
        "            vscode.postMessage({ type: 'clearChat' });",
        "            setStatus('confirming clear...', 'st-wait');",
        "        } else if (val === 'settings') {",
        "            vscode.postMessage({ type: 'openSettings' });",
        "            setStatus('opening setup...', 'st-wait');",
        "        }",
        "    });",
        "}",
        "if (modelSelect) {",
        "    modelSelect.addEventListener('change', function () {",
        "        var sel = modelSelect.value;",
        "        vscode.postMessage({ type: 'selectModel', model: sel });",
        "        logLine('selected model: ' + sel);",
        "    });",
        "}",

        // ---- Input controls (Send / Stop / keyboard) ----
        "send.addEventListener('click', function () {",
        "    var text = input.value.trim();",
        "    if (!text) { return; }",
        "    var selectedModel = modelSelect ? modelSelect.value : '';",
        "    addMessage('user', text);",
        "    vscode.postMessage({ type: 'userMessage', text: text, model: selectedModel });",
        "    var dup = promptHistory.indexOf(text);",
        "    if (dup !== -1) { promptHistory.splice(dup, 1); }",
        "    promptHistory.push(text);",
        "    historyIndex = promptHistory.length;",
        "    pendingDraft = '';",
        "    input.value = '';",
        "    sendDraftNow();",
        "    saveViewState();",
        "    send.disabled = true;",
        "    agentRunning = true;",
        "    if (stop) { stop.disabled = false; }",
        "    setStatus('waiting for agent...', 'st-wait');",
        "});",
        "if (stop) {",
        "    stop.addEventListener('click', function () {",
        "        vscode.postMessage({ type: 'stop' });",
        "        stop.disabled = true;",
        "        setStatus('stopping...', 'st-wait');",
        "    });",
        "}",
        "input.addEventListener('keydown', function (e) {",
        "    if (e.key === 'Enter' && !e.shiftKey) { e.preventDefault(); send.click(); return; }",
        "    if (e.key === 'ArrowUp' && !e.shiftKey && !e.altKey && !e.ctrlKey && !e.metaKey) {",
        "        if (canNavigateHistoryUp() && historyOlder()) { e.preventDefault(); }",
        "    } else if (e.key === 'ArrowDown' && !e.shiftKey && !e.altKey && !e.ctrlKey && !e.metaKey) {",
        "        if (canNavigateHistoryDown() && historyNewer()) { e.preventDefault(); }",
        "    }",
        "});",

        // ---- File attachment (@ mentions + [+] button) ----
        // The host collects open editor tabs and runs the native file dialog;
        // the webview just renders the popup and inserts a `@path` token. The
        // host expands @ mentions into inline file contents before sending the
        // message to the model, so the agent can read the attached file.
        "function hideAttachMenu() {",
        "    if (fileAttachMenu) { fileAttachMenu.style.display = 'none'; fileAttachMenu.innerHTML = ''; }",
        "    attachAtPos = -1;",
        "}",
        "function insertFileRef(filePath) {",
        "    if (!input) { return; }",
        "    var val = input.value;",
        "    var insertText = '@' + filePath + ' ';",
        "    if (attachAtPos >= 0) {",
        "        var before = val.substring(0, attachAtPos);",
        "        var after = val.substring(input.selectionStart || attachAtPos);",
        "        input.value = before + insertText + after;",
        "        input.selectionStart = input.selectionEnd = before.length + insertText.length;",
        "    } else {",
        "        var start = input.selectionStart || val.length;",
        "        input.value = val.substring(0, start) + insertText + val.substring(start);",
        "        input.selectionStart = input.selectionEnd = start + insertText.length;",
        "    }",
        "    hideAttachMenu();",
        "    input.focus();",
        "    sendDraftDebounced();",
        "    saveViewState();",
        "}",
        "function renderAttachMenu(files) {",
        "    if (!fileAttachMenu) { return; }",
        "    fileAttachMenu.innerHTML = '';",
        "    var browseItem = document.createElement('div');",
        "    browseItem.className = 'file-item';",
        "    browseItem.innerHTML = '<span class=\"browse-icon\">📁</span> <span>Browse files...</span>';",
        "    browseItem.addEventListener('click', function() {",
        "        hideAttachMenu();",
        "        vscode.postMessage({ type: 'browseFile' });",
        "    });",
        "    fileAttachMenu.appendChild(browseItem);",
        "    if (Array.isArray(files) && files.length > 0) {",
        "        files.forEach(function(f) {",
        "            var item = document.createElement('div');",
        "            item.className = 'file-item';",
        "            item.innerHTML = '<span>📄</span> <span class=\"file-path\">' + f + '</span>';",
        "            item.addEventListener('click', function() { insertFileRef(f); });",
        "            fileAttachMenu.appendChild(item);",
        "        });",
        "    }",
        "    fileAttachMenu.style.display = 'flex';",
        "}",
        "if (addFileBtn) {",
        "    addFileBtn.addEventListener('click', function(e) {",
        "        e.stopPropagation();",
        "        attachAtPos = input ? input.selectionStart : -1;",
        "        vscode.postMessage({ type: 'requestOpenFiles' });",
        "    });",
        "}",
        "if (input) {",
        "    input.addEventListener('input', function(e) {",
        "        var pos = input.selectionStart || 0;",
        "        var charBefore = input.value.charAt(pos - 1);",
        "        if (charBefore === '@') {",
        "            attachAtPos = pos - 1;",
        "            vscode.postMessage({ type: 'requestOpenFiles' });",
        "        } else if (fileAttachMenu && fileAttachMenu.style.display !== 'none' && charBefore === ' ') {",
        "            hideAttachMenu();",
        "        }",
        "    });",
        "}",
        "document.addEventListener('click', function(e) {",
        "    if (fileAttachMenu && !fileAttachMenu.contains(e.target) && e.target !== addFileBtn) {",
        "        hideAttachMenu();",
        "    }",
        "});",
        "logLine('shell script loaded');",
    ].join("\n");
}