/**
 * Webview "shell" script: element refs, persisted state (draft/height/scroll),
 * Up/Down prompt history, setup-overlay wiring, status/debug helpers, model
 * dropdown, boot handshake, and input controls (Send/Stop/keyboard).
 *
 * Concatenated with markdown.ts and messages.ts into one <script> block by
 * html.ts. This part must come FIRST (it opens with "use strict" and declares
 * the shared variables used by the other parts).
 *
 * Pure string builder — no vscode dependency, unit-testable.
 * NOTE: no template literals (see Handoff-Summary.md lessons learned).
 */

export function buildWebviewScript(): string {
    return [
        '"use strict";',
        "var vscode = acquireVsCodeApi();",
        "var statusEl = document.getElementById('status');",
        "var messages = document.getElementById('messages');",
        "var input = document.getElementById('input');",
        "var inputGrip = document.getElementById('inputGrip');",
        "var send = document.getElementById('send');",
        "var stop = document.getElementById('stop');",
        "var modelSelect = document.getElementById('modelSelect');",
        "var refreshModels = document.getElementById('refreshModels');",
        "var timeModels = document.getElementById('timeModels');",
        "var compactBtn = document.getElementById('compactBtn');",
        "var settingsBtn = document.getElementById('settingsBtn');",
        "var setupOverlay = document.getElementById('setupOverlay');",
        "var setupBaseUrl = document.getElementById('setupBaseUrl');",
        "var setupAuthType = document.getElementById('setupAuthType');",
        "var setupAuthLabel = document.getElementById('setupAuthLabel');",
        "var setupAuthValue = document.getElementById('setupAuthValue');",
        "var setupTestBtn = document.getElementById('setupTestBtn');",
        "var setupStatus = document.getElementById('setupStatus');",
        "var setupModelSelect = document.getElementById('setupModelSelect');",
        "var setupMaxSteps = document.getElementById('setupMaxSteps');",
        "var setupSaveBtn = document.getElementById('setupSaveBtn');",
        "var debugToggle = document.getElementById('debugToggle');",
        "var debugWrap = document.getElementById('debugWrap');",
        "var line = 0;",
        "var knownModels = [];",
        "var timings = {};",
        // ---- Webview state persistence (survives view hide/show cycles) ----
        // vscode.getState()/setState() persist across webview disposal for
        // the same view, so the input draft, input height, and scroll
        // position can be restored when the view is shown again.
        "var agentRunning = false;",
        "var savedState = null;",
        "try { savedState = vscode.getState(); } catch (e) { savedState = null; }",
        "var heightApplied = false;",
        "if (savedState && typeof savedState.draft === 'string' && input) { input.value = savedState.draft; }",
        "if (savedState && typeof savedState.inputHeight === 'number' && savedState.inputHeight >= 48 && input) {",
        "    input.style.height = savedState.inputHeight + 'px';",
        "    heightApplied = true;",
        "}",
        // ---- Prompt history (Up/Down navigation) ----
        // promptHistory holds submitted prompts (oldest first). historyIndex
        // points at the currently shown entry; promptHistory.length is the
        // 'new prompt' slot. pendingDraft preserves unsent text while the
        // user browses history.
        "var promptHistory = [];",
        "var historyIndex = 0;",
        "var pendingDraft = '';",
        "var draftTimer = null;",
        "var heightTimer = null;",
        "function sendDraftNow() {",
        "    try { vscode.postMessage({ type: 'draftChange', text: input ? input.value : '' }); } catch (e) {}",
        "}",
        "function sendDraftDebounced() {",
        "    if (draftTimer) { clearTimeout(draftTimer); }",
        "    draftTimer = setTimeout(sendDraftNow, 300);",
        "}",
        "function sendHeightNow() {",
        "    if (!input) { return; }",
        "    var h = input.getBoundingClientRect().height;",
        "    if (h > 0) { try { vscode.postMessage({ type: 'inputHeightChange', height: Math.round(h) }); } catch (e) {} }",
        "}",
        "function saveViewState() {",
        "    try {",
        "        var atBottom = messages ? (messages.scrollHeight - messages.scrollTop - messages.clientHeight < 40) : true;",
        "        vscode.setState({",
        "            draft: input ? input.value : '',",
        "            scrollTop: messages ? messages.scrollTop : 0,",
        "            atBottom: atBottom,",
        "            inputHeight: input ? Math.round(input.getBoundingClientRect().height) : 0",
        "        });",
        "    } catch (e) {}",
        "}",
        "if (window.ResizeObserver && input) {",
        "    new ResizeObserver(function () {",
        "        if (heightTimer) { clearTimeout(heightTimer); }",
        "        heightTimer = setTimeout(sendHeightNow, 400);",
        "    }).observe(input);",
        "}",
        "if (input) {",
        "    input.addEventListener('input', function () { sendDraftDebounced(); saveViewState(); });",
        "}",
        "if (messages) { messages.addEventListener('scroll', saveViewState); }",
        // ---- Input box resize grip (drag to resize) ----
        // The grip sits on the top edge of #inputArea. Dragging the mouse UP
        // grows the input (its top edge rises); dragging DOWN shrinks it. The
        // resulting height is clamped to the textarea's CSS min-height (48px)
        // and max-height (60vh), then persisted through the existing
        // sendHeightNow() / saveViewState() plumbing so it survives view
        // hide/show cycles and reloads. Window-level move/up listeners (guarded
        // by gripDragging) keep the drag alive even if the pointer leaves the
        // small grip hit area; setPointerCapture is used as a best-effort nicety.
        "var gripDragging = false;",
        "var gripStartY = 0;",
        "var gripStartHeight = 0;",
        "function gripClampHeight(h) {",
        "    var maxH = Math.round((window.innerHeight || 0) * 0.6);",
        "    if (h < 48) { return 48; }",
        "    if (h > maxH) { return maxH; }",
        "    return h;",
        "}",
        "if (inputGrip) {",
        "    inputGrip.addEventListener('pointerdown', function (e) {",
        "        if (!input) { return; }",
        "        e.preventDefault();",
        "        gripDragging = true;",
        "        gripStartY = e.clientY;",
        "        gripStartHeight = Math.round(input.getBoundingClientRect().height);",
        "        inputGrip.classList.add('grip-active');",
        "        try { inputGrip.setPointerCapture(e.pointerId); } catch (err) {}",
        "    });",
        "}",
        "window.addEventListener('pointermove', function (e) {",
        "    if (!gripDragging || !input) { return; }",
        "    e.preventDefault();",
        "    var newH = gripClampHeight(gripStartHeight + (gripStartY - e.clientY));",
        "    input.style.height = newH + 'px';",
        "});",
        "window.addEventListener('pointerup', function () {",
        "    if (!gripDragging) { return; }",
        "    gripDragging = false;",
        "    if (inputGrip) { inputGrip.classList.remove('grip-active'); }",
        "    sendHeightNow();",
        "    saveViewState();",
        "});",
        "window.addEventListener('pointercancel', function () {",
        "    if (!gripDragging) { return; }",
        "    gripDragging = false;",
        "    if (inputGrip) { inputGrip.classList.remove('grip-active'); }",
        "    sendHeightNow();",
        "    saveViewState();",
        "});",
        "function caretToEnd() {",
        "    try { input.selectionStart = input.selectionEnd = input.value.length; } catch (e) {}",
        "}",
        "function caretOnFirstLine() {",
        "    var pos = input.selectionStart || 0;",
        "    return input.value.substring(0, pos).indexOf('\\n') === -1;",
        "}",
        "function caretOnLastLine() {",
        "    var pos = input.selectionEnd || 0;",
        "    return input.value.substring(pos).indexOf('\\n') === -1;",
        "}",
        "function historyOlder() {",
        "    if (!input || promptHistory.length === 0 || historyIndex === 0) { return false; }",
        "    if (historyIndex === promptHistory.length) { pendingDraft = input.value; }",
        "    historyIndex--;",
        "    input.value = promptHistory[historyIndex];",
        "    caretToEnd();",
        "    sendDraftDebounced();",
        "    saveViewState();",
        "    return true;",
        "}",
        "function historyNewer() {",
        "    if (!input || historyIndex >= promptHistory.length) { return false; }",
        "    historyIndex++;",
        "    if (historyIndex === promptHistory.length) {",
        "        input.value = pendingDraft;",
        "    } else {",
        "        input.value = promptHistory[historyIndex];",
        "    }",
        "    caretToEnd();",
        "    sendDraftDebounced();",
        "    saveViewState();",
        "    return true;",
        "}",
        // ---- Setup overlay wiring ----
        "function updateSetupAuthInput(authType, authValue, apiKeyStored) {",
        "  if (!setupAuthLabel || !setupAuthValue) { return; }",
        "  if (authType === 'env') {",
        "    setupAuthLabel.textContent = 'Env Var Name'; setupAuthValue.placeholder = 'e.g. OPENAI_API_KEY'; setupAuthValue.type = 'text';",
        "    if (authValue !== undefined) { setupAuthValue.value = authValue; }",
        "  } else {",
        "    setupAuthLabel.textContent = 'API Key'; setupAuthValue.type = 'password';",
        "    setupAuthValue.placeholder = apiKeyStored ? 'Stored securely; enter only to replace' : 'sk-...';",
        "    if (authValue !== undefined) { setupAuthValue.value = ''; }",
        "  }",
        "}",
        "if(setupAuthType) {",
        "  setupAuthType.addEventListener('change', function() {",
        "    updateSetupAuthInput(this.value, '', false);",
        "  });",
        "}",
        "if(setupTestBtn) {",
        "  setupTestBtn.addEventListener('click', function() {",
        "    setupStatus.textContent = 'Testing...'; setupStatus.style.color = 'var(--vscode-descriptionForeground)';",
        "    vscode.postMessage({ type: 'testConnection', baseUrl: setupBaseUrl.value, authType: setupAuthType.value, authValue: setupAuthValue.value });",
        "  });",
        "}",
        "if(setupSaveBtn) {",
        "  setupSaveBtn.addEventListener('click', function() {",
        "    vscode.postMessage({ type: 'saveSetup', baseUrl: setupBaseUrl.value, authType: setupAuthType.value, authValue: setupAuthValue.value, model: setupModelSelect.value, maxSteps: setupMaxSteps ? setupMaxSteps.value : '15' });",
        "  });",
        "}",
        // ---- Status banner / debug log ----
        "function setStatus(t, cls) {",
        "    if (statusEl) { statusEl.textContent = t;",
        "        statusEl.className = cls || 'st';",
        "        statusEl.style.display = 'block'; }",
        "}",
        "function logLine(t) {",
        "    line++;",
        "    var d = document.createElement('div');",
        "    d.textContent = line + ': ' + t;",
        "    d.className = 'dbg';",
        "    var dbg = document.getElementById('debug');",
        "    if (dbg) { dbg.appendChild(d); dbg.scrollTop = dbg.scrollHeight; }",
        "}",
        "if (debugToggle && debugWrap) {",
        "    debugToggle.addEventListener('click', function () {",
        "        var collapsed = debugWrap.classList.toggle('collapsed');",
        "        debugToggle.textContent = collapsed ? '▸ debug log' : '▾ debug log';",
        "    });",
        "}",
        // ---- Model dropdown helpers ----
        "function labelFor(m) {",
        "    var t = timings[m];",
        "    if (t === undefined) { return m; }",
        "    if (t === null) { return m + '  (timing...)'; }",
        "    if (t < 0) { return m + '  (failed)'; }",
        "    return m + '  (' + t + ' ms)';",
        "}",
        "function renderModelOptions() {",
        "    if (!modelSelect) { return; }",
        "    var keep = modelSelect.value;",
        "    modelSelect.innerHTML = '';",
        "    knownModels.forEach(function (m) {",
        "        var opt = document.createElement('option');",
        "        opt.value = m;",
        "        opt.textContent = labelFor(m);",
        "        if (m === keep) { opt.selected = true; }",
        "        modelSelect.appendChild(opt);",
        "    });",
        "}",
        "function updateModelOptions(models, selected) {",
        "    if (!modelSelect) { return; }",
        "    var list = Array.isArray(models) ? models.slice() : [];",
        "    if (selected && list.indexOf(selected) === -1) {",
        "        list.unshift(selected);",
        "    }",
        "    if (list.length === 0 && selected) {",
        "        list.push(selected);",
        "    }",
        "    knownModels = list;",
        "    modelSelect.innerHTML = '';",
        "    list.forEach(function (m) {",
        "        var opt = document.createElement('option');",
        "        opt.value = m;",
        "        opt.textContent = labelFor(m);",
        "        if (m === selected) { opt.selected = true; }",
        "        modelSelect.appendChild(opt);",
        "    });",
        "}",
        // ---- Boot handshake ----
        "window.onerror = function (msg, src, l, c) {",
        "    var t = 'SCRIPT ERROR: ' + msg + ' @' + l + ':' + c;",
        "    setStatus('SCRIPT ERROR (see debug)', 'st-err');",
        "    logLine(t);",
        "    try { vscode.postMessage({ type: 'webviewError', text: t }); } catch (e) {}",
        "    return false;",
        "};",
        "logLine('script started');",
        "setStatus('WEBVIEW ALIVE - script running', 'st-ok');",
        "try {",
        "    vscode.postMessage({",
        "        type: 'webviewReady',",
        "        draft: input ? input.value : '',",
        "        height: input ? Math.round(input.getBoundingClientRect().height) : 0",
        "    });",
        "    logLine('webviewReady sent');",
        "}",
        "catch (e) { logLine('postMessage failed: ' + e); }",
        // ---- Header button listeners ----
        "if (refreshModels) {",
        "    refreshModels.addEventListener('click', function () {",
        "        vscode.postMessage({ type: 'fetchModels' });",
        "        setStatus('fetching models...', 'st-wait');",
        "    });",
        "}",
        "if (timeModels) {",
        "    timeModels.addEventListener('click', function () {",
        "        timeModels.disabled = true;",
        "        knownModels.forEach(function (m) { timings[m] = null; });",
        "        renderModelOptions();",
        "        vscode.postMessage({ type: 'benchmarkModels' });",
        "        setStatus('measuring model response times...', 'st-wait');",
        "    });",
        "}",
        "if (compactBtn) {",
        "    compactBtn.addEventListener('click', function () {",
        "        compactBtn.disabled = true;",
        "        vscode.postMessage({ type: 'compact' });",
        "        setStatus('compacting context...', 'st-wait');",
        "    });",
        "}",
        "if (settingsBtn) {",
        "    settingsBtn.addEventListener('click', function () {",
        "        vscode.postMessage({ type: 'openSettings' });",
        "        setStatus('opening setup...', 'st-wait');",
        "    });",
        "}",
        "if (modelSelect) {",
        "    modelSelect.addEventListener('change', function () {",
        "        var sel = modelSelect.value;",
        "        vscode.postMessage({ type: 'selectModel', model: sel });",
        "        logLine('selected model: ' + sel);",
        "    });",
        "}",
        // ---- Input controls (Send / Stop / keyboard) ----
        // addMessage comes from messages.ts; function declarations hoist
        // across the concatenated script, so it is available here.
        "send.addEventListener('click', function () {",
        "    var text = input.value.trim();",
        "    if (!text) { return; }",
        "    var selectedModel = modelSelect ? modelSelect.value : '';",
        "    addMessage('user', text);",
        "    vscode.postMessage({ type: 'userMessage', text: text, model: selectedModel });",
        "    var dup = promptHistory.indexOf(text);",
        "    if (dup !== -1) { promptHistory.splice(dup, 1); }",
        "    promptHistory.push(text);",
        "    historyIndex = promptHistory.length;",
        "    pendingDraft = '';",
        "    input.value = '';",
        "    sendDraftNow();",
        "    saveViewState();",
        "    send.disabled = true;",
        "    agentRunning = true;",
        "    if (stop) { stop.disabled = false; }",
        "    setStatus('waiting for agent...', 'st-wait');",
        "});",
        "if (stop) {",
        "    stop.addEventListener('click', function () {",
        "        vscode.postMessage({ type: 'stop' });",
        "        stop.disabled = true;",
        "        setStatus('stopping...', 'st-wait');",
        "    });",
        "}",
        "input.addEventListener('keydown', function (e) {",
        "    if (e.key === 'Enter' && !e.shiftKey) { e.preventDefault(); send.click(); return; }",
        "    if (e.key === 'ArrowUp' && !e.shiftKey && !e.altKey && !e.ctrlKey && !e.metaKey) {",
        "        if (caretOnFirstLine() && historyOlder()) { e.preventDefault(); }",
        "    } else if (e.key === 'ArrowDown' && !e.shiftKey && !e.altKey && !e.ctrlKey && !e.metaKey) {",
        "        if (caretOnLastLine() && historyNewer()) { e.preventDefault(); }",
        "    }",
        "});",
        "logLine('shell script loaded');",
    ].join("\n");
}