/**
 * The webview stylesheet.
 *
 * Pure string builder — no vscode dependency, unit-testable.
 * NOTE: no template literals (see Handoff-Summary.md lessons learned).
 */

export function buildWebviewCss(lightIconUri: string, darkIconUri: string): string {
    return [
        ":root { color-scheme: light dark; }",
        "body { font-family: var(--vscode-font-family);",
        "  font-size: var(--vscode-font-size);",
        "  color: var(--vscode-foreground);",
        "  margin: 0; display: flex; flex-direction: column; height: 100vh; }",
        "#modelHeader { display: flex; align-items: center; gap: 6px; padding: 6px 8px;",
        "  border-bottom: 1px solid var(--vscode-panel-border); font-size: 11px; }",
        "#modelSelect { flex: 1; background: var(--vscode-dropdown-background);",
        "  color: var(--vscode-dropdown-foreground); border: 1px solid var(--vscode-dropdown-border);",
        "  padding: 3px 6px; font-size: 11px; border-radius: 2px; }",
        "#refreshModels, #timeModels, #compactBtn { background: var(--vscode-button-secondaryBackground, var(--vscode-button-background));",
        "  color: var(--vscode-button-secondaryForeground, var(--vscode-button-foreground));",
        "  border: none; padding: 3px 8px; cursor: pointer; border-radius: 2px; font-size: 11px; }",
        "#refreshModels:hover, #timeModels:hover, #compactBtn:hover { opacity: 0.8; }",
        "#timeModels:disabled, #compactBtn:disabled { opacity: 0.4; cursor: default; }",
        "#status { display: none; padding: 4px 8px; font-size: 11px;",
        "  font-family: monospace; }",
        ".st-ok { background: #104a10; color: #c8f7c8; display: block; }",
        ".st-err { background: #5a1010; color: #ffd6d6; display: block; }",
        ".st-wait { background: #4a4210; color: #fff3c8; display: block; }",
        ".st { display: block; }",
        "#debugWrap { border-top: 1px dashed var(--vscode-panel-border); }",
        "#debugToggle { padding: 2px 8px; font-size: 10px; font-family: monospace;",
        "  color: var(--vscode-descriptionForeground); cursor: pointer; user-select: none; }",
        "#debugToggle:hover { color: var(--vscode-foreground); }",
        "#debugWrap.collapsed #debug { display: none; }",
        "#debug { max-height: 90px; overflow-y: auto; font-size: 10px;",
        "  font-family: monospace; color: var(--vscode-descriptionForeground); }",
        ".dbg { white-space: pre-wrap; }",
        "#messages { flex: 1; overflow-y: auto; padding: 8px; }",
        ".msg { margin: 6px 0; padding: 8px 10px; border-radius: 6px;",
        "  width: 100%; box-sizing: border-box; overflow-wrap: break-word; }",
        ".msg.user { background: var(--vscode-input-background); }",
        ".msg.assistant { background: var(--vscode-editorWidget-background); }",
        ".msg.error { color: var(--vscode-errorForeground); }",
        ".msg > pre { margin: 0; white-space: pre-wrap; font-family: inherit; }",
        ".md { line-height: 1.5; overflow: hidden; }",
        ".md > :first-child { margin-top: 0; }",
        ".md > :last-child { margin-bottom: 0; }",
        ".md p { margin: 6px 0; }",
        ".md h1, .md h2, .md h3, .md h4, .md h5, .md h6 { margin: 12px 0 6px 0; line-height: 1.3; }",
        ".md h1 { font-size: 1.3em; border-bottom: 1px solid var(--vscode-panel-border); padding-bottom: 3px; }",
        ".md h2 { font-size: 1.18em; }",
        ".md h3 { font-size: 1.08em; }",
        ".md h4, .md h5, .md h6 { font-size: 1em; }",
        ".md ul, .md ol { margin: 6px 0; padding-left: 22px; }",
        ".md li { margin: 2px 0; }",
        ".md blockquote { margin: 6px 0; padding: 2px 10px;",
        "  border-left: 3px solid var(--vscode-panel-border);",
        "  color: var(--vscode-descriptionForeground); }",
        ".md hr { border: none; border-top: 1px solid var(--vscode-panel-border); margin: 10px 0; }",
        ".md a { color: var(--vscode-textLink-foreground); }",
        ".md .md-code { font-family: var(--vscode-editor-font-family, monospace);",
        "  background: var(--vscode-textCodeBlock-background); border-radius: 3px;",
        "  padding: 1px 4px; font-size: 0.92em; }",
        ".md-codeblock { margin: 8px 0; border: 1px solid var(--vscode-panel-border);",
        "  border-radius: 4px; overflow: hidden; }",
        ".md-codeblock .md-codehead { padding: 2px 8px; font-size: 10px; font-family: monospace;",
        "  color: var(--vscode-descriptionForeground);",
        "  background: var(--vscode-editorWidget-background);",
        "  border-bottom: 1px solid var(--vscode-panel-border); }",
        ".md-codeblock pre { margin: 0; padding: 8px 10px; overflow: auto; max-height: 420px;",
        "  background: var(--vscode-textCodeBlock-background); white-space: pre;",
        "  font-family: var(--vscode-editor-font-family, monospace); font-size: 12px; line-height: 1.45; }",
        ".hl-cmt { color: #008000; font-style: italic; }",
        ".hl-str { color: #a31515; }",
        ".hl-num { color: #098658; }",
        ".hl-kw { color: #0000ff; }",
        ".hl-lit { color: #0000ff; }",
        ".hl-typ { color: #267f99; }",
        ".hl-fn { color: #795e26; }",
        ".hl-var { color: #001080; }",
        ".hl-atr { color: #e50000; }",
        ".hl-tag { color: #800000; }",
        ".hl-dec { color: #795e26; }",
        ".hl-op { color: #000000; }",
        ".hl-pun { color: #3b3b3b; }",
        "body.vscode-dark .hl-cmt, body.vscode-high-contrast .hl-cmt { color: #6a9955; }",
        "body.vscode-dark .hl-str, body.vscode-high-contrast .hl-str { color: #ce9178; }",
        "body.vscode-dark .hl-num, body.vscode-high-contrast .hl-num { color: #b5cea8; }",
        "body.vscode-dark .hl-kw, body.vscode-high-contrast .hl-kw { color: #569cd6; }",
        "body.vscode-dark .hl-lit, body.vscode-high-contrast .hl-lit { color: #569cd6; }",
        "body.vscode-dark .hl-typ, body.vscode-high-contrast .hl-typ { color: #4ec9b0; }",
        "body.vscode-dark .hl-fn, body.vscode-high-contrast .hl-fn { color: #dcdcaa; }",
        "body.vscode-dark .hl-var, body.vscode-high-contrast .hl-var { color: #9cdcfe; }",
        "body.vscode-dark .hl-atr, body.vscode-high-contrast .hl-atr { color: #9cdcfe; }",
        "body.vscode-dark .hl-tag, body.vscode-high-contrast .hl-tag { color: #569cd6; }",
        "body.vscode-dark .hl-dec, body.vscode-high-contrast .hl-dec { color: #dcdcaa; }",
        "body.vscode-dark .hl-op, body.vscode-high-contrast .hl-op { color: #d4d4d4; }",
        "body.vscode-dark .hl-pun, body.vscode-high-contrast .hl-pun { color: #a8a8a8; }",
        ".md-tablewrap { overflow-x: auto; margin: 8px 0; }",
        ".md-table { border-collapse: collapse; font-size: 0.95em; }",
        ".md-table th, .md-table td { border: 1px solid var(--vscode-panel-border); padding: 4px 10px; }",
        ".md-table th { background: var(--vscode-editorWidget-background); }",
        ".msg.tool { background: transparent; padding: 0; overflow: hidden;",
        "  border: 1px solid var(--vscode-panel-border); }",
        ".tool-head { display: flex; align-items: center; gap: 6px; padding: 4px 8px;",
        "  cursor: pointer; background: var(--vscode-textCodeBlock-background);",
        "  font-family: var(--vscode-editor-font-family, monospace); font-size: 11px; user-select: none; }",
        ".tool-head:hover { background: var(--vscode-list-hoverBackground, rgba(128,128,128,0.12)); }",
        ".chev { display: inline-block; width: 12px; color: var(--vscode-descriptionForeground); }",
        ".tool-name { font-weight: bold; white-space: nowrap; }",
        ".tool-preview { color: var(--vscode-descriptionForeground); overflow: hidden;",
        "  text-overflow: ellipsis; white-space: nowrap; flex: 1; min-width: 0; }",
        ".tool-status { color: var(--vscode-charts-green, #3fb950); margin-left: auto;",
        "  padding-left: 8px; white-space: nowrap; }",
        ".tool-body { border-top: 1px solid var(--vscode-panel-border); }",
        ".tool-body pre { margin: 0; padding: 8px 10px; overflow: auto; max-height: 300px;",
        "  white-space: pre-wrap; font-family: var(--vscode-editor-font-family, monospace); font-size: 11px; }",
        "#inputArea { display: flex; gap: 6px; padding: 8px; align-items: flex-end;",
        "  border-top: 1px solid var(--vscode-panel-border); }",
        "#input { flex: 1; background: var(--vscode-input-background);",
        "  color: var(--vscode-input-foreground);",
        "  border: 1px solid var(--vscode-input-border); padding: 6px;",
        "  resize: vertical; min-height: 48px; max-height: 60vh; overflow-y: auto; }",
        "#send { background: var(--vscode-button-background);",
        "  color: var(--vscode-button-foreground); border: none;",
        "  padding: 6px 14px; cursor: pointer; flex-shrink: 0; }",
        "#send:disabled { opacity: 0.5; cursor: default; }",
        "#stop { background: var(--vscode-errorForeground); color: white; border: none;",
        "  padding: 6px 14px; cursor: pointer; flex-shrink: 0; }",
        "#stop:disabled { opacity: 0.4; cursor: default; }",
        ".my-theme-icon { content: url('" + lightIconUri + "'); width: 24px; height: 24px; }",
        "body.vscode-dark .my-theme-icon, body.vscode-high-contrast .my-theme-icon { content: url('" + darkIconUri + "'); }",
        "#setupOverlay { display: none; position: absolute; top: 0; left: 0; width: 100%; height: 100%; box-sizing: border-box; background: var(--vscode-sideBar-background); z-index: 9999; padding: 15px; overflow-y: auto; flex-direction: column; gap: 12px; }",
        ".s-field { display: flex; flex-direction: column; gap: 6px; }",
        ".s-field label { font-weight: bold; font-size: 11px; }",
        ".s-field input, .s-field select { background: var(--vscode-input-background); color: var(--vscode-input-foreground); border: 1px solid var(--vscode-input-border); padding: 6px; font-size: 11px; box-sizing: border-box; width: 100%; }",
        ".s-btn { background: var(--vscode-button-background); color: var(--vscode-button-foreground); border: none; padding: 8px; cursor: pointer; font-size: 11px; width: 100%; }",
        ".s-btn:hover { background: var(--vscode-button-hoverBackground); }",
        ".s-btn:disabled { opacity: 0.5; cursor: default; }"
    ].join("\n");
}